version: '1.0'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=web-app-docker
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - PORT=8000
      - HOST=mysql
      - USER_NAME=root
      - USER_PASS=123456
    ports:
      - "8000:8000"

  client:
    container_name: client
    image: nginx:1.23.4-alpine
    depends_on:
      - server
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"

networks:
  backend:
  frontend:


